/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mgaigalas.cowboys;

public class Application {
    public static void main(String[] args) {
        final var processor = new Processor();
        processor.process();
    }
}
